services:
  ollama-phi:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5666:80
    depends_on:
      - server
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - ollama-phi
      - chromadb
    restart: always
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - 8000:8000
    volumes:
      - ./chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=TRUE
    restart: always